# Makefile.alarm:
#
# A makefile used to build the alarm code and test it on the local system
#
####
ROOT_DIR = ..

.PHONY: run_alarm_test
run_alarm_test: bin/alarm_test
	bin/alarm_test

bin/alarm_test: $(ROOT_DIR)/Core/Src/ventilator/alarm.c $(ROOT_DIR)/Core/Src/ventilator/initialize.c $(ROOT_DIR)/Core/Src/ventilator/sound.c $(ROOT_DIR)/Core/Inc/ventilator/sound.h $(ROOT_DIR)/Core/Inc/ventilator/alarm.h ./alarm_test.c ./test.h ./test.c
	mkdir -p bin
	gcc -g -std=c99 -DSTATIC="" -I$(ROOT_DIR)/Core/Inc -I$(ROOT_DIR)/ventilator-sw-common/Inc -I$(ROOT_DIR)/Test $(ROOT_DIR)/Core/Src/ventilator/alarm.c $(ROOT_DIR)/Core/Src/ventilator/initialize.c $(ROOT_DIR)/Core/Src/ventilator/sound.c ./alarm_test.c ./test.c -o bin/alarm_test
