####
# Makefile.state_tester:
#
# A makefile used to build the sound code and test it on the local system
#
####
ROOT_DIR = ..

.PHONY: run_state_tester_test
run_state_tester_test: bin/state_tester_test
	bin/state_tester_test


SRC_FILES = $(ROOT_DIR)/Core/Src/ventilator/alarm.c \
	$(ROOT_DIR)/Core/Src/ventilator/sound.c \
	$(ROOT_DIR)/Core/Src/ventilator/display.c \
	$(ROOT_DIR)/Core/Src/ventilator/numerical.c \
	$(ROOT_DIR)/Core/Src/ventilator/bargraph.c \
	$(ROOT_DIR)/Core/Src/ventilator/button.c \
	$(ROOT_DIR)/Core/Src/ventilator/mcp23017.c \
	$(ROOT_DIR)/Core/Src/ventilator/test_cycle.c \
	./test.c \
	./state_tester_test.c

HDR_FILES =	$(ROOT_DIR)/Core/Inc/ventilator/watchdog.h \
	$(ROOT_DIR)/Core/Inc/ventilator/alarm.h \
	$(ROOT_DIR)/Core/Inc/ventilator/sound.h \
	$(ROOT_DIR)/Core/Inc/ventilator/display.h \
	$(ROOT_DIR)/Core/Inc/ventilator/numerical.h \
	$(ROOT_DIR)/Core/Inc/ventilator/bargraph.h \
	$(ROOT_DIR)/Core/Inc/ventilator/button.h \
	$(ROOT_DIR)/Core/Inc/ventilator/mcp23017.h \
	$(ROOT_DIR)/Core/Inc/ventilator/test_cycle.h \
	$(ROOT_DIR)/ventilator-sw-common/Inc/swassert.h \
	./test.h


bin/state_tester_test: $(SRC_FILES) $(HDR_FILES)
	mkdir -p bin
	gcc -g -g -std=c99 -DSTATIC="" -I$(ROOT_DIR)/Core/Inc -I$(ROOT_DIR)/ventilator-sw-common/Inc -I$(ROOT_DIR)/Test $(SRC_FILES) -o bin/state_tester_test


