####
# Makefile.controller:
#
# A makefile used to build the controller code and test it on the local system
#
####
ROOT_DIR = ..

.PHONY: run_controller_test
run_controller_test: bin/controller_test
	bin/controller_test

bin/controller_test: $(ROOT_DIR)/Core/Src/ventilator/controller.c $(ROOT_DIR)/Core/Inc/ventilator/controller.h ./controller_test.c ./test.h ./test.c
	mkdir -p bin
	gcc -g -std=c99 -DSTATIC="" -I$(ROOT_DIR)/Core/Inc -I$(ROOT_DIR)/ventilator-sw-common/Inc -I$(ROOT_DIR)/Test $(ROOT_DIR)/Core/Src/ventilator/controller.c ./controller_test.c ./test.c -o bin/controller_test
